#!/bin/bash
while read oldrev newrev ref
do
        if [[ $ref =~ .*/master$ ]];
        then
                echo "Master ref received. Deploying master branch..."
                git --work-tree=/var/www/backend --git-dir=/var/repo/backend checkout -f
        else
                echo "Ref $ref successfully received. Doing nothing: only the master branch may be deployed on this server."
        fi
done

